name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push: # trigger on push
    branches: [ master ]
  pull_request: # trigger on PR
    branches: [ master ]
  workflow_dispatch: # enable manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1"

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: build
        run: |
          luarocks install luacheck
          luacheck .
